name: islam_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line

  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.14

  percent_indicator: ^4.0.0
  photo_view: ^0.13.0
  #  path_provider: ^2.0.9
  provider: ^6.0.2
  cupertino_icons: ^1.0.4
  image_picker: ^0.8.5
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  package_info: ^2.0.2
  url_launcher: ^6.1.0
  show_up_animation: ^2.0.0
  lottie: ^1.2.2
  liquid_progress_indicator: ^0.4.0
  skeletons: ^0.0.3
  flutter_rating_bar: ^4.0.0
  file_picker: ^4.5.1
  custom_pop_up_menu: ^1.2.3+1
  cached_network_image: ^3.2.0
  share_plus: ^4.0.3
  open_store: ^0.2.4
  app_settings: ^4.1.5
  connectivity_plus: ^2.2.1
  another_flushbar: ^1.10.28
  syncfusion_flutter_charts: ^20.1.50
  fl_chart: ^0.50.1

  #  flutter_app_icon_badge: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
#  flutter_native_splash: ^2.1.1
#
#
## run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
#  flutter pub run flutter_native_splash:remove


#flutter_native_splash:
#  image: assets/splash_400.png
#  android: true
#  ios: true
#  android_gravity: center
#  ios_content_mode: center
#  background_image: "assets/splash_full.png"
#

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - assets/fonts/
    - assets/app_setting_json.json
    - assets/splash_400.png
    - assets/splash_full.png



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
